### PR TITLE
Additional images for Mana, Sakuya, Sophitia, and Yuna

### PR DESCRIPTION
**Pull request by Arndress**
Thank you for merging the previous pull request! This motivated me to spend time hunting down a fresh image update for a few more characters. I ran out of steam after four characters, but I am confident that these new images are a high quality set that represents the best of the years since the game was in active development.

It's possible I might feel compelled to do the same for the remaining characters in some future year. But for this year, this is all I have to give.

### CODE REVIEW

**Comment by BlueWinds** [comment]
Hey, good work - I'm always wary when people have image suggestions, because I've learned in general people have terrible taste, but you did great here. :)

Looks like you may be missing updates to `sophitia/base.js` to match the new images there?

**Comment by Arndress** [comment]
Thanks! I try to adhere to the general guidelines you had when the game was being first developed, looking for good-quality images, uncensored where possible, that don't contradict the story setting and are generally flexible for storytelling. Plus the dimension and size requirements. I also tried to remove any text where I could. I appreciate the actual subject material can be subjective at times, though!

I've added a new commit with the Sophitia base.js updated, which I previously overlooked. Thanks for noticing this.

**Comment by BlueWinds** [comment]
Will make a release of this later today or tomorrow.

**Comment by BlueWinds** [comment]
Removing text is something I've changed my mind on over they years - I've come around to the idea that leaving artists watermarks is important. Not important enough to go back and change things in old games, but it's something I tend not to do in my newer work anymore.

**Comment by Arndress** [comment]
I can respect that. I'll keep this in mind if I make any future contributions.

**Pull request merged**
